---
title: "D2M ICMA Notebook"
output: html_notebook
author: "Jacob Scharago"
date:"2026-09-03"
---

# ICMA 9-17-2026
```{r}
install.packages("nycflights13")
library(nycflights13)
flights <- nycflights13::flights
glimpse(flights)
flights |> 
  # distance is miles, time is minutes
  # convert to miles/hour using *60
  mutate(speed = distance/air_time * 60,
       .before = 1) |> 
head()

flights |> 
  mutate(speed = distance/air_time * 60,
       .after = distance) |> 
  glimpse()

flights |> 
  select(year, month, day, contains("dep"))

flights |> 
  mutate(speed = distance/air_time * 60,
       .after = distance) |> 
   select(year, month, day,
          dep_time, air_time, distance, speed)

flights |> 
  mutate(speed = distance/air_time * 60,
       .after = distance) |> 
   select(year, month, day,how_fast=speed)

flights |> 
  rename(dep_airport = origin,
         arr_airport = dest)

flights |> 
  relocate(carrier,
           .after = day)

flights |> 
  group_by(month) |> 
  head()

flights |> 
  group_by(month) |> 
  count()

flights |> 
  group_by(month) |> 
  summarise(avg_delay = mean(dep_delay))

flights |> 
  group_by(month) |> 
  summarise(avg_delay = mean(dep_delay,
                             na.rm = TRUE)) |> round(2)

flights |> 
  group_by(month, day) |> 
  count()

flights_grouped <- flights |> 
  group_by(month)

flights_grouped |> 
  count()

flights |> 
  count()

flights_grouped |> 
  ungroup()

flights |> 
  group_by(month) |> 
  slice_max(dep_delay, n = 2)
```
```{r}
flights |> 
  group_by(month) |> 
  summarize(mean_delay = mean(arr_delay, na.rm = TRUE),
            sd_delay = sd(arr_delay, na.rm = TRUE),
            number_late = sum (dep_delay > 0, na.rm = TRUE),
            total_number = n()) |> 
  mutate(percentage = number_late/total_number) |> 
  ggplot(aes(y = percentage, x = month)) +
  geom_line() +
scale_x_continuous(breaks = 1:12) +
  ylim(0, 0.55)
```



# ICMA 9-15-2026
```{r}
PlantGrowth |>
  ggplot(aes(y = weight,x = group)) +
  geom_boxplot(width = 0.2)
```
```{r}
install.packages("nycflights13")
library(nycflights13)
flights <- nycflights13::flights
glimpse(flights)

flights |> 
  filter(month == 1)

flights |> 
  filter(month == 1 & day == 1)

flights |> 
  arrange(year, month, day, dep_time)

flights |> 
  arrange(desc(month))
```
```{r}
i < flights |> 
filter(arr_delay > 120 & dep_delay <= 0) 
  arrange(dep_delay)
  
j < flights |> 
  arrange(dep_delay) |> 
  filter(arr_delay > 120 & dep_delay <= 0) 

all(i==j)
```
```{r}
#| label: setup
#| include: false

library(tidyverse)
library(palmerpenguins)
```

# ICMA 9-10-2026

```{r}
ggplot(data=penguins, mapping = aes(x= flipper_length_mm,
                                    y= bill_length_mm)) + 
  geom_point()
```

```{r}
PlantGrowth
ggplot(data=PlantGrowth,
       mapping=aes(y=weight,x=group)) +
  geom_point(alpha=0.5) + 
  stat_summary(geom= "pointrange",
               fun.dat= "mean_se",
               color="purple")
```
Yes, this is tidy data

# ICMA 9-3-2026

plot(cars)
```


I notice that distance increases with speed and that most inidviduals are scattered between 10-20
